### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by kaloronahuang** [koryako/changeface#1]
```
ted: OOM when allocating tensor with shape[32,64,128,128]
Traceback (most recent call last):
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,64,128,128]
         [[Node: training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@model_3/conv2d_32/convolution"], data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Shape, conv2d_32/kernel/read, training_1/Adam/gradients/model_3/conv2d_32/Sigmoid_grad/SigmoidGrad)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 89, in <module>
    loss_B = autoencoder_B.train_on_batch([warped_B,mask_B], [target_B,mask_B])
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\engine\training.py", line 1832, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\backend\tensorflow_backend.py", line 2352, in __call__
    **self.session_kwargs)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,64,128,128]
         [[Node: training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@model_3/conv2d_32/convolution"], data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Shape, conv2d_32/kernel/read, training_1/Adam/gradients/model_3/conv2d_32/Sigmoid_grad/SigmoidGrad)]]

Caused by op 'training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Conv2DBackpropInput', defined at:
  File "train.py", line 89, in <module>
    loss_B = autoencoder_B.train_on_batch([warped_B,mask_B], [target_B,mask_B])
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\engine\training.py", line 1831, in train_on_batch
    self._make_train_function()
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\optimizers.py", line 415, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\optimizers.py", line 73, in get_gradients
    grads = K.gradients(loss, params)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\backend\tensorflow_backend.py", line 2389, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 560, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 368, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 560, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\nn_grad.py", line 368, in _Conv2DGrad
    op.get_attr("data_format")),
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 496, in conv2d_backprop_input
    data_format=data_format, name=name)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

...which was originally created as op 'model_3/conv2d_32/convolution', defined at:
  File "train.py", line 54, in <module>
    from model import autoencoder_A
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Source\deep_learning\toolkit\version33\model.py", line 158, in <module>
    autoencoder_B = Model( [x2,m2], decoder_B( encoder(x2) ) )
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\engine\topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\engine\topology.py", line 2061, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\engine\topology.py", line 2212, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\layers\convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\keras\backend\tensorflow_backend.py", line 3189, in conv2d
    data_format=tf_data_format)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 661, in convolution
    op=op)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 331, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "C:\Users\ny_st\Anaconda3\envs\FSGAN\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 653, in op
    name=name)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,64,128,128]
         [[Node: training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@model_3/conv2d_32/convolution"], data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](training_1/Adam/gradients/model_3/conv2d_32/convolution_grad/Shape, conv2d_32/kernel/read, training_1/Adam/gradients/model_3/conv2d_32/Sigmoid_grad/SigmoidGrad)]]

2018-02-21 13:31:38.595464: E c:\l\work\tensorflow-1.1.0\tensorflow\stream_executor\cuda\cuda_gpu_executor.cc:628] Deallocating stream with pending work
```
I don't think there is something with my hardware for I own a GTX 1080 as my gpu. I just ran only this model. Hope you can check it.

**Comment by kaloronahuang** [comment]
Ok i figured it out, i reduced the batch size so that i can make my gpu get this done
